version: "3.9"
services:
  gateway:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
    command: uvicorn services.gateway.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
