openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /generate:
    post:
      summary: Generate
      operationId: generate_generate_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/bulk_create:
    post:
      summary: Bulk Create
      operationId: bulk_create_api_bulk_create_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkCreateResponse'
  /product-categories:
    get:
      summary: Product Categories
      operationId: product_categories_product_categories_get
      parameters:
      - name: category
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Category
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /design-ideas:
    get:
      summary: Design Ideas
      operationId: design_ideas_design_ideas_get
      parameters:
      - name: category
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Category
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /product-suggestions:
    get:
      summary: Product Suggestions
      operationId: product_suggestions_product_suggestions_get
      parameters:
      - name: category
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Category
      - name: design
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Design
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    BulkCreateResponse:
      properties:
        created:
          items:
            additionalProperties: true
            type: object
          type: array
          title: Created
        errors:
          items:
            additionalProperties: true
            type: object
          type: array
          title: Errors
      type: object
      required:
      - created
      - errors
      title: BulkCreateResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
