from __future__ import annotations

from typing import Any


def assemble_products(ideas: list[dict[str, Any]], images: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Build the product payload shared by gateway and orchestrator flows."""

    idea_lookup = {idea.get("id"): idea for idea in ideas if idea.get("id") is not None}
    products: list[dict[str, Any]] = []
    for image in images:
        idea_id = image.get("idea_id")
        idea = idea_lookup.get(idea_id)
        if not idea:
            continue

        base_tags = [idea.get("term"), idea.get("category"), image.get("category")]
        tags = [tag for tag in {tag for tag in base_tags if tag}]
        products.append(
            {
                "id": image.get("id"),
                "idea_id": idea_id,
                "title": (idea.get("description") or idea.get("term", "Design")).strip()[:120]
                or "Automated POD Listing",
                "description": idea.get("description") or "Generated by POD Automator",
                "image_url": image.get("image_url"),
                "category": image.get("category") or idea.get("category"),
                "tags": tags,
                "price": idea.get("suggested_price") or 24.99,
            }
        )

    return products
