name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8
      - name: Pytest
        run: pytest
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install Node dependencies
        working-directory: client
        run: npm ci
      - name: Run Node tests
        working-directory: client
        run: npm test
      - name: Install Playwright
        working-directory: client
        run: npx playwright install --with-deps
      - name: Playwright tests
        run: npx playwright test
